{{- if not .Values.slackWebhookUrlSecretKeyRef -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8-alerts.fullname" . }}
  labels:
    {{- include "k8-alerts.labels" . | nindent 4 }}
type: Opaque
data:
  slackWebhookUrl: {{ required "slackWebhookUrl is required" .Values.slackWebhookUrl | b64enc | quote }}
{{- end -}}
