# permissions for end users to edit charts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chart-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-helm
    app.kubernetes.io/part-of: operator-helm
    app.kubernetes.io/managed-by: kustomize
  name: chart-editor-role
rules:
- apiGroups:
  - k8alerts.my.domain
  resources:
  - charts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8alerts.my.domain
  resources:
  - charts/status
  verbs:
  - get
